name: Publish release
description: Creates a signed annotated tag and GitHub Release, and merges the release branch into main for stable releases

inputs:
    app-id:
        description: The GitHub App ID for authentication
        required: true
    app-private-key:
        description: The GitHub App private key for authentication
        required: true

runs:
    using: composite
    steps:
        - name: Configure git bot
          id: git-bot
          uses: dnd-mapp/.github/.github/actions/configure-git-bot@d2fbf089d21d131c8a37219d17567cde172c2c06
          with:
              app-id: ${{ inputs.app-id }}
              app-private-key: ${{ inputs.app-private-key }}

        - name: Publish release
          id: publish-release
          shell: bash
          working-directory: ${{ github.action_path }}
          env:
              GH_TOKEN: ${{ steps.git-bot.outputs.token }}
              CHANGELOG_PATH: ${{ github.workspace }}/CHANGELOG.md
          run: node dist/publish-release.cjs

        - name: Merge release branch
          if: startsWith(github.ref_name, 'release/') && steps.publish-release.outputs.is-prerelease == 'false'
          shell: bash
          working-directory: ${{ github.action_path }}
          env:
              GH_TOKEN: ${{ steps.git-bot.outputs.token }}
              RELEASE_BRANCH: ${{ github.ref_name }}
          run: node dist/merge-release-branch.cjs
