name: CI
description: Runs Continuous Integration checks
runs:
    using: composite
    steps:
        - name: Set up tools
          uses: ./.github/actions/setup-tools

        - name: Check formatting
          shell: bash
          run: pnpm format:check

        - name: Run linting
          shell: bash
          run: pnpm lint

        - name: Check built artifacts are up-to-date
          shell: bash
          run: pnpm build:check

        - name: Run tests
          shell: bash
          run: pnpm test
