name: Publish release
on:
    workflow_call:
        secrets:
            app-id:
                required: true
            app-private-key:
                required: true
jobs:
    publish-release:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
              with:
                  fetch-depth: 2

            - name: Set up tools
              uses: dnd-mapp/.github/.github/actions/setup-tools@c35024782aba3e8ea1043eeb5c25353a9751d69e

            - name: Check version change
              id: version-check
              shell: bash
              run: |
                  CURRENT=$(jq -r .version package.json)
                  PREVIOUS=$(git show HEAD~1:package.json | jq -r .version)

                  if [ "$CURRENT" = "$PREVIOUS" ]; then
                      echo "changed=false" >> "$GITHUB_OUTPUT"
                  else
                      echo "changed=true" >> "$GITHUB_OUTPUT"
                  fi

            - name: Publish release
              if: steps.version-check.outputs.changed == 'true'
              uses: dnd-mapp/.github/.github/actions/publish-release@c35024782aba3e8ea1043eeb5c25353a9751d69e
              with:
                  app-id: ${{ secrets.app-id }}
                  app-private-key: ${{ secrets.app-private-key }}
