name: Release
on:
    workflow_call:
        inputs:
            version:
                required: true
                type: string
            prerelease-id:
                default: none
                type: string
        secrets:
            app-id:
                required: true
            app-private-key:
                required: true
jobs:
    bump-version:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Set up tools
              uses: dnd-mapp/.github/.github/actions/setup-tools@fb7d2cb1e259f65c841cac6dd9a84896068e9f7a

            - name: Bump version
              uses: dnd-mapp/.github/.github/actions/bump-version@fb7d2cb1e259f65c841cac6dd9a84896068e9f7a
              with:
                  app-id: ${{ secrets.app-id }}
                  app-private-key: ${{ secrets.app-private-key }}
                  version: ${{ inputs.version }}
                  prerelease-id: ${{ inputs.prerelease-id }}
